apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: abax
  template:
    metadata:
      labels:
        app: abax-app
    spec:
      containers:
      - name: abaximg
        image: teste-abax
        ports:
        - containerPort: 80